# python docker containers used: https://hub.docker.com/_/python/

test_on_linux_task:
  container:
    matrix:
      image: python:3.7
      image: python:3.6
      image: python:3.5
      image: python:3.4
      image: python:2.7
  test_script: make test

test_on_windows_task:
  windows_container:
    matrix:
      image: python:3.7-windowsservercore
      image: python:3.6-windowsservercore
      image: python:2.7-windowsservercore
  pip_cache:
    folder: ~/.cache/pip
    fingerprint_script:
      - echo %PYTHON_VERSION%
      - type tests\\requirements.txt
    populate_script: pip install --user -r tests\\requirements.txt
  test_script: pytest
